-- SYNTAX TEST "SQL (Jinja).sublime-syntax"

-- My dynamic {{ comment }}!
-- ^^^^^^^^^^^^^^^^^^^^^^^^^^ meta.template.jinja comment.line.double-dash.sql
--            ^^^^^^^^^^^^^ meta.embedded.expression.jinja
--            ^^ punctuation.section.embedded.begin.jinja
--              ^^^^^^^^^ source.jinja.embedded
--                       ^^ punctuation.section.embedded.end.jinja


   SELECT {{ columns | secure }} FROM { {{ table }} } WHERE `my-{{field}}` is "String {{ value }}"
--^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ meta.template.jinja
-- ^^^^^^ keyword.other.DML.sql
--        ^^^^^^^^^^^^^^^^^^^^^^ meta.embedded.expression.jinja
--        ^^ punctuation.section.embedded.begin.jinja
--          ^^^^^^^^^^^^^^^^^^ source.jinja.embedded
--           ^^^^^^^ variable.other.readwrite.jinja
--                   ^^^^^^^^ meta.filter.jinja
--                   ^ keyword.operator.symbol.jinja keyword.operator.assignment.pipe.jinja
--                     ^^^^^^ meta.function-call.identifier.jinja variable.function.filter.jinja
--                            ^^ punctuation.section.embedded.end.jinja
--                               ^^^^ keyword.other.DML.sql
--                                      ^^^^^^^^^^^ meta.embedded.expression.jinja
--                                      ^^ punctuation.section.embedded.begin.jinja
--                                        ^^^^^^^ source.jinja.embedded
--                                         ^^^^^ variable.other.readwrite.jinja
--                                               ^^ punctuation.section.embedded.end.jinja
--                                                    ^^^^^ keyword.other.DML.sql
--                                                          ^^^^ string.quoted.other.backtick.sql
--                                                          ^ punctuation.definition.string.begin.sql
--                                                              ^^^^^^^^^ meta.embedded.expression.jinja
--                                                              ^^ punctuation.section.embedded.begin.jinja
--                                                                ^^^^^ source.jinja.embedded variable.other.readwrite.jinja
--                                                                     ^^ punctuation.section.embedded.end.jinja
--                                                                       ^ string.quoted.other.backtick.sql punctuation.definition.string.end.sql
--                                                                         ^^ keyword.operator.logical.sql
--                                                                            ^^^^^^^^ string.quoted.double.sql
--                                                                            ^ punctuation.definition.string.begin.sql
--                                                                                    ^^^^^^^^^^^ meta.embedded.expression.jinja
--                                                                                    ^^ punctuation.section.embedded.begin.jinja
--                                                                                      ^^^^^^^ source.jinja.embedded
--                                                                                       ^^^^^ variable.other.readwrite.jinja
--                                                                                             ^^ punctuation.section.embedded.end.jinja
--                                                                                               ^ string.quoted.double.sql punctuation.definition.string.end.sql
