name: Syntax Tests

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - '.github/workflows/syntax_test.yml'
      - '**/syntax_test_*'
      - '**/*.sublime-syntax'
      - '**/*.tmPreferences'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/syntax_test.yml'
      - '**/syntax_test_*'
      - '**/*.sublime-syntax'
      - '**/*.tmPreferences'
  workflow_dispatch:

jobs:
  run_syntax_tests:
    name: Sublime Text ${{ matrix.build }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: 4107
            default_packages: v4107
          - build: 4126
            default_packages: v4126
          - build: 4143
            default_packages: v4143
          - build: 4152
            default_packages: v4152
          - build: 4169
            default_packages: v4169
          - build: latest
            default_packages: master
    steps:
      - name: Checkout Default Packages
        uses: actions/checkout@v4
        with:
          repository: sublimehq/Packages
          ref: ${{ matrix.default_packages }}
          path: st_syntax_tests/Data/Packages
      - name: Delete default package tests
        run: |-
          find st_syntax_tests/Data/Packages/*/ -type f -name 'syntax_test*' -exec rm -v '{}' \;
      - name: Checkout Jinja2
        uses: actions/checkout@v4
        with:
          path: st_syntax_tests/Data/Packages/Jinja2
      - name: Run Syntax Tests for Sublime Text ${{ matrix.build }}
        run: |-
          if [[ "${{ matrix.build }}" == "latest" ]]; then
            wget -O st_syntax_tests.tar.xz https://download.sublimetext.com/latest/dev/linux/x64/syntax_tests
          else
            wget -O st_syntax_tests.tar.xz https://download.sublimetext.com/st_syntax_tests_build_${{ matrix.build }}_x64.tar.xz
          fi
          tar xf st_syntax_tests.tar.xz
          cd st_syntax_tests
          ./syntax_tests
